AWSTemplateFormatVersion: '2010-09-09'
Description: Creates ECS services for Django and FastAPI.

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  DjangoContainerPort:
    Type: Number
    Default: 80
  FastAPIContainerPort:
    Type: Number
    Default: 81
  DesiredTaskCount:
    Type: Number
    Default: 2
    Description: Number of tasks to run initially
    MinValue: 0
  ECSCluster:
    Type: String
    Description: ECS Cluster name or ARN
  DjangoTaskDefinitionArn:
    Type: String
    Description: ARN of the Django task definition
  FastAPITaskDefinitionArn:
    Type: String
    Description: ARN of the FastAPI task definition
  TargetGroup1:
    Type: String
    Description: ARN of Django target group
  TargetGroup3:
    Type: String
    Description: ARN of FastAPI target group
  ECSSecurityGroup:
    Type: String
    Description: ECS security group ID
  PrivateSubnets:
    Type: String
    Description: Comma-separated list of private subnet IDs

Resources:
  DjangoService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${ProjectName}-${Environment}-django
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredTaskCount
      TaskDefinition: !Ref DjangoTaskDefinitionArn
      DeploymentController:
        Type: ECS
      LoadBalancers:
        - ContainerName: django
          ContainerPort: !Ref DjangoContainerPort
          TargetGroupArn: !Ref TargetGroup1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            Fn::Split:
              - ','
              - !Ref PrivateSubnets

  FastAPIService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${ProjectName}-${Environment}-fastapi
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredTaskCount
      TaskDefinition: !Ref FastAPITaskDefinitionArn
      DeploymentController:
        Type: ECS
      LoadBalancers:
        - ContainerName: fastapi
          ContainerPort: !Ref FastAPIContainerPort
          TargetGroupArn: !Ref TargetGroup3
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            Fn::Split:
              - ','
              - !Ref PrivateSubnets

Outputs:
  DjangoServiceName:
    Value: !Ref DjangoService
  FastAPIServiceName:
    Value: !Ref FastAPIService

